apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: mysql:8.0

          args:
           - "--innodb-buffer-pool-size=64M"
           - "--innodb-log-buffer-size=8M"
           - "--key-buffer-size=8M"
           - "--max-connections=20"
           - "--performance-schema=OFF"


          ports:
            - containerPort: 3306

          env:

            - name: MALLOC_ARENA_MAX
              value: "2"

            - name: MALLOC_TRIM_THRESHOLD_
              value: "131072"

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "1"        
